config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users, skip: [:sessions],
    controllers: {
      omniauth_callbacks: 'users/omniauth_callbacks'
    }

  root 'static_pages#home'
  get  '/about',     to: 'static_pages#about'
  get  '/signup',    to: 'users#new'
  post '/signup',    to: 'users#create'
  get  '/login',     to: 'sessions#new'
  post '/login',     to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :account_activations, only: [:edit]
  resources :microposts,          only: [:create, :destroy]
  resources :relationships,       only: [:create, :destroy]
  resources :password_edit,       only: [:edit, :update]
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    if logged_in?
      @micropost  = current_user.microposts.build
      @feed_items = current_user.feed.paginate(page: params[:page])
    end
  end
  
  def about
  end
end

app/views/static_pages/about.html.erb
<% provide(:title, "About") %>
<h1>INSTACLONE APPについて</h1>
<p style="text-align:center;">
  本サイトはポートフォリオとして作成されたものであり、サイトの修正が随時行われます。<br>
  非公開とすることもございますので、その旨ご留意ください。
</p>

app/views/static_pages/home.html.erb
<% if logged_in? %>
  <div class="row">
    <h3>Micropost Feed</h3>
    <div class="col-md-9">
      <%= render 'shared/feed' %>
    </div>
    <aside class="col-md-3">
      <section class="user_info">
        <%= render 'shared/user_info' %>
      </section>
      <section class="stats">
        <%= render 'shared/stats' %>
      </section>
      <section class="micropost_form">
        <%= render 'shared/micropost_form' %>
      </section>
    </aside>
  </div>
<% else %>
  <div class="center jumbotron">
    <h1>INSTACLONE APP</h1>
    <h2>
      友達の写真や動画をチェックしよう
    </h2>
    <p>
      <%= link_to "ユーザー登録", signup_path,
          class: "btn btn-lg btn-primary" %>
    </p>
    <p>
      <%= link_to "Facebookでログイン", user_facebook_omniauth_authorize_path,
          class: "btn btn-lg btn-primary" %>
    </p>
    <br>
    <p>
      アカウントをお持ちの方<br>
      ※アカウント情報をログイン画面に記載しています<br>
      <%= link_to "ログイン", login_path,
          class: "btn btn-lg btn-primary" %>
    </p>
  </div>
<% end %>